services:
  backend:
    image: demo-mern-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    networks:
      - demo-mern-networks
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
  frontend:
    image: demo-mern-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - demo-mern-networks
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    links:
      - backend

  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - demo-mern-networks
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - demo-mern-networks
networks:
  demo-mern-networks: